### ISSUE TITLE
How would you setup localized sites with CME?

### ISSUE THREAD

**Issue by alexagui** [nystudio107/craft-multi-environment#1]
Following the [official docs](https://craftcms.com/docs/localization-guide) having a little trouble figuring out how to configure `es` site.

I was thinking of duplicating index.php into `/es` and then have it reference an `.env.es.php` file.

**Comment by alexagui** [comment]
Here's how I got my Spanish site loading.

1. I went with **Example 2** from [Step 5](https://craftcms.com/docs/localization-guide#step-5-set-up-the-files) of the localization guide.

So this folder structure:

```
craft/
public/            --> example.com/
    .htaccess
    index.php
    es/                 --> example.com/es/
        .htaccess
        index.php
```

2. At root of your project, duplicate `.env.php` as `.env.es.php`

Update line 43 `SITE_URL` as 
`'SITE_URL' => $protocol . $_SERVER['HTTP_HOST'] . '/es/',`

3. Make the following updates to public/es/index.php

lines 4-5
```
// Load the local Craft environment
if (file_exists('../../.env.es.php'))
    require_once '../../.env.es.php';
```

lines 11-12
```
// Path to your craft/ folder
$craftPath = '../../craft';
define('CRAFT_LOCALE', 'es');
```

Now this approach seems a bit redundant (especially if you have multiple locales).  So If anyone has a better idea then please share.

**Comment by khalwat** [comment]
Yep, that's certainly one way you can do it.
