### ISSUE TITLE
https server variable is not always set

### ISSUE THREAD

**Issue by ockam** [nystudio107/craft-multi-environment#2]
I have an issue where Seomatic return a canonical url with http instead of https.

I trace it back to `$_SERVER['https']` not being set.

This [SO  article](http://stackoverflow.com/questions/11650640/why-isnt-serverhttps-set-to-1) suggest that it may not be set when using a load balancer or proxy.

It also suggest using `$_SERVER['HTTP_X_FORWARDED_PROTO']`.

I did some testing on my server:
```
isset($_SERVER['https']) = 
$_SERVER['SERVER_PORT'] = 80
$_SERVER['HTTP_USESSL'] = 
$_SERVER['HTTP_X_FORWARDED_PROTO'] = https
```
So maybe you should add `HTTP_X_FORWARDED_PROTO` as a fallback.

**Comment by ockam** [comment]
Here’s what I used:
```
// The site url to use; it can be hard-coded as well
putenv('CRAFTENV_SITE_URL=' . ((isset($_SERVER['HTTPS']) or (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) and $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')) ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . '/');

// The base url environmentVariable to use for Assets; it can be hard-coded as well
putenv('CRAFTENV_BASE_URL=' . ((isset($_SERVER['HTTPS']) or (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) and $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')) ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . '/');

```

**Comment by khalwat** [comment]
Yep, I ended changing it to be something similar.
